repositories = [

    "https://github.com/spf13/hyde.git",
    "https://github.com/tummychow/lanyon-hugo.git",
    "https://github.com/AlexFinn/simple-a.git",
    "https://github.com/eliasson/liquorice.git",
    "https://github.com/dplesca/purehugo.git",
    "https://github.com/gizak/nofancy.git",
    "https://github.com/jaden/twentyfourteen.git",
    "https://github.com/keichi/vienna.git",
    "https://github.com/azmelanar/hugo-theme-pixyll.git",
    "https://github.com/progrhyme/hugo-theme-bootie-docs.git",
    "https://github.com/zhe/hugo-theme-slim.git",
    "https://github.com/pdevty/material-design.git",
    "https://github.com/pdevty/polymer.git",
    "https://github.com/syui/hugo-theme-air.git",
    "https://github.com/garvincasimir/hugo-h5bp-simple.git",
    "https://github.com/allnightgrocery/hugo-theme-blueberry-detox.git",
    "https://github.com/chipsenkbeil/grid-side.git",
    "https://github.com/brycematheson/allegiant.git",
    "https://github.com/jbub/ghostwriter.git",
    "https://github.com/htdvisser/hugo-base16-theme.git",
    "https://github.com/parsiya/Hugo-Octopress.git",
    "https://github.com/halogenica/beautifulhugo.git",
    "https://github.com/jpescador/hugo-future-imperfect.git",
    "https://github.com/aerohub/hugo-identity-theme.git",
    "https://github.com/matcornic/hugo-theme-learn.git",
    "https://github.com/wowchemy/starter-academic.git",
    "https://github.com/jrutheiser/hugo-lithium-theme.git",
    "https://github.com/syui/hugo-theme-wave.git",
    "https://github.com/schmanat/hugo-highlights-theme.git",
    "https://github.com/damiencaselli/paperback.git",
    "https://github.com/devcows/hugo-universal-theme.git",
    "https://github.com/aerohub/hugrid.git",
    "https://github.com/ExchangeRate-API/strange-case.git",
    "https://github.com/lasseborly/anybodyhome.git",
    "https://github.com/IvanChou/hugo-theme-vec.git",
    "https://github.com/aerohub/hugo-faq-theme.git",
    "https://github.com/aerohub/hugo-orbit-theme.git",
    "https://github.com/LordMathis/hugo-theme-nix.git",
    "https://github.com/shenoybr/hugo-goa.git",
    "https://github.com/vimux/blank.git",
    "https://github.com/bep/docuapi.git",
    "https://github.com/alanorth/hugo-theme-bootstrap4-blog.git",
    "https://github.com/dldx/hpstr-hugo-theme.git",
    "https://github.com/kakawait/hugo-tranquilpeak-theme.git",
    "https://github.com/kishaningithub/hugo-creative-portfolio-theme.git",
    "https://github.com/tblyler/light-hugo.git",
    "https://github.com/the2ne/hugo-frais.git",
    "https://github.com/saey55/hugo-elate-theme.git",
    "https://github.com/lubang/hugo-hello-programmer-theme.git",
    "https://github.com/leonhe/hugo_eiio.git",
    "https://github.com/hdcdstr8fwd/foundation-theme.git",
    "https://github.com/Vimux/mainroad.git",
    "https://github.com/nurlansu/hugo-sustain.git",
    "https://github.com/davidhampgonsalves/hugo-black-and-light-theme.git",
    "https://github.com/nodejh/hugo-theme-cactus-plus.git",
    "https://github.com/carsonip/hugo-theme-minos.git",
    "https://github.com/thomasheller/crab.git",
    "https://github.com/vickylaixy/hugo-theme-introduction.git",
    "https://github.com/frjo/hugo-theme-zen.git",
    "https://github.com/wd/hugo-fabric.git",
    "https://github.com/jeblister/kube.git",
    "https://github.com/budparr/gohugo-theme-ananke.git",
    "https://github.com/gyorb/hugo-dusk.git",
    "https://github.com/gesquive/slate.git",
    "https://github.com/MunifTanjim/minimo.git",
    "https://github.com/yihui/hugo-xmin.git",
    "https://github.com/balaramadurai/hugo-travelify-theme.git",
    "https://github.com/yursan9/manis-hugo-theme.git",
    "https://github.com/calintat/minimal.git",
    "https://github.com/goodroot/hugo-classic.git",
    "https://github.com/yihui/hugo-xmag.git",
    "https://github.com/damiencaselli/hugo-journal.git",
    "https://github.com/olOwOlo/hugo-theme-even.git",
    "https://github.com/felicianotech/hugo-theme-lean-launch-page.git",
    "https://github.com/SteveLane/hugo-icon.git",
    "https://github.com/ribice/kiss.git",
    "https://github.com/jweslley/hugo-conference.git",
    "https://github.com/Lednerb/bilberry-hugo-theme.git",
    "https://github.com/schollz/onetwothree.git",
    "https://github.com/funkydan2/hugo-kiera.git",
    "https://github.com/MarcusVirg/forty.git",
    "https://github.com/escalate/hugo-split-theme.git",
    "https://github.com/eshlox/simplicity.git",
    "https://github.com/RealOrangeOne/hugo-theme-revealjs.git",
    "https://github.com/meibenny/elephants.git",
    "https://github.com/it-gro/hugo-theme-w3css-basic.git",
    "https://github.com/curttimson/hugo-theme-massively.git",
    "https://github.com/eddiewebb/hugo-resume.git",
    "https://github.com/xianmin/hugo-theme-jane.git",
    "https://github.com/luizdepra/hugo-coder.git",
    "https://github.com/jsnjack/kraiklyn.git",
    "https://github.com/hivickylai/hugo-theme-sam.git",
    "https://github.com/htr3n/hyde-hyde.git",
    "https://github.com/nanxiaobei/hugo-paper.git",
    "https://github.com/appernetic/hugo-nederburg-theme.git",
    "https://github.com/diwao/hestia-pure.git",
    "https://github.com/miguelsimoni/hugo-initio.git",
    "https://github.com/curttimson/hugo-theme-dopetrope.git",
    "https://github.com/fiatjaf/classless-hugo.git",
    "https://github.com/lucperkins/hugo-fresh.git",
    "https://github.com/themefisher/airspace-hugo.git",
    "https://github.com/xaviablaza/hugo-lodi-theme.git",
    "https://github.com/Xzya/hugo-material-blog.git",
    "https://github.com/tnwhitwell/hugo-startpage-theme.git",
    "https://github.com/kishaningithub/hugo-shopping-product-catalogue-simple.git",
    "https://github.com/funkydan2/alpha-church.git",
    "https://github.com/lingxz/er.git",
    "https://github.com/dzello/reveal-hugo.git",
    "https://github.com/sudorook/capsule.git",
    "https://github.com/nathancday/min_night.git",
    "https://github.com/serg/yourfolio.git",
    "https://github.com/themefisher/vex-hugo.git",
    "https://github.com/huyb1991/hugo-lamp.git",
    "https://github.com/salcan/BeyondNothing.git",
    "https://github.com/antonpolishko/hugo-stellar-theme.git",
    "https://github.com/zhaohuabing/hugo-theme-cleanwhite.git",
    "https://github.com/qqhann/hugo-primer.git",
    "https://github.com/themefisher/navigator-hugo.git",
    "https://github.com/uicardiodev/hugo-sodium-theme.git",
    "https://github.com/gundamew/hugo-bingo.git",
    "https://github.com/panr/hugo-theme-hello-friend.git",
    "https://github.com/shaform/hugo-theme-den.git",
    "https://github.com/d-kusk/minimage.git",
    "https://github.com/EmielH/tale-hugo.git",
    "https://github.com/cssandstuff/hugo-theme-winning.git",
    "https://github.com/marcanuy/simpleit-hugo-theme.git",
    "https://github.com/blankoworld/hugo_theme_adam_eve.git",
    "https://github.com/Tazeg/hugo-blog-jeffprod.git",
    "https://github.com/themefisher/timer-hugo.git",
    "https://github.com/natarajmb/charaka-hugo-theme.git",
    "https://github.com/salsysd/hugo-assembly.git",
    "https://github.com/liuzc/LeaveIt.git",
    "https://github.com/xaprb/story.git",
    "https://github.com/naro143/hugo-coder-portfolio.git",
    "https://github.com/nirocfz/arabica.git",
    "https://github.com/runningstream/hugograyscale.git",
    "https://github.com/uicardiodev/hugo-lime.git",
    "https://github.com/VVelox/hugo-dusky-neon-potato.git",
    "https://github.com/hauke96/hugo-theme-hamburg.git",
    "https://github.com/uicardiodev/hugo-uilite.git",
    "https://github.com/bul-ikana/hugo-cards.git",
    "https://github.com/AngeloStavrow/indigo.git",
    "https://github.com/SAGGameDeveloper/hugo-minimalist-spa.git",
    "https://github.com/lgaida/mediumish-gohugo-theme.git",
    "https://github.com/zwbetz-gh/minimal-bootstrap-hugo-theme.git",
    "https://github.com/gkmngrgn/hugo-alageek-theme.git",
    "https://github.com/alex-shpak/hugo-book.git",
    "https://github.com/themefisher/meghna-hugo.git",
    "https://github.com/jnjosh/internet-weblog.git",
    "https://github.com/shankar/hugo-grapes.git",
    "https://github.com/themefisher/infinity-hugo.git",
    "https://github.com/mikeblum/hugo-now.git",
    "https://github.com/Track3/hermit.git",
    "https://github.com/EmielH/hallo-hugo.git",
    "https://github.com/spech66/bootstrap-bp-hugo-theme.git",
    "https://github.com/wileybaba/hugo-theme-robotico.git",
    "https://github.com/jesselau76/hugo-w3-simple.git",
    "https://github.com/geschke/hugo-tikva.git",
    "https://github.com/joway/hugo-theme-yinyang.git",
    "https://github.com/thingsym/hugo-theme-techdoc.git",
    "https://github.com/mazgi/hugo-theme-techlog-simple.git",
    "https://github.com/gonnux/hugo-apps-theme.git",
    "https://github.com/zerostaticthemes/hugo-serif-theme.git",
    "https://github.com/josephhutch/aether.git",
    "https://github.com/mattbutton/silhouette-hugo.git",
    "https://github.com/darshanbaral/sada.git",
    "https://github.com/spookey/slick.git",
    "https://github.com/2-REC/hugo-myportfolio-theme.git",
    "https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme.git",
    "https://github.com/JugglerX/hugo-hero-theme.git",
    "https://github.com/cfrome77/hugo-theme-sky.git",
    "https://github.com/ijsucceed/onepress.git",
    "https://github.com/fncnt/vncnt-hugo.git",
    "https://github.com/gethugothemes/dot-hugo-documentation-theme.git",
    "https://github.com/guangmean/Niello.git",
    "https://github.com/danielkvist/hugo-terrassa-theme.git",
    "https://github.com/vaga/hugo-theme-m10c.git",
    "https://github.com/seanlane/gochowdown.git",
    "https://github.com/panr/hugo-theme-terminal.git",
    "https://github.com/zwbetz-gh/cupper-hugo-theme.git",
    "https://github.com/siegerts/hugo-theme-basic.git",
    "https://github.com/jimfrenette/hugo-starter.git",
    "https://github.com/coderzh/hugo-pacman-theme.git",
    "https://github.com/rhazdon/hugo-theme-hello-friend-ng.git",
    "https://github.com/de-souza/hugo-flex.git",
    "https://github.com/Fastbyte01/KeepIt.git",
    "https://github.com/GDGToulouse/devfest-theme-hugo.git",
    "https://github.com/zwbetz-gh/papercss-hugo-theme.git",
    "https://github.com/onweru/hugo-swift-theme.git",
    "https://github.com/darshanbaral/mero.git",
    "https://github.com/Vimux/Binario.git",
    "https://github.com/darshanbaral/aafu.git",
    "https://github.com/iCyris/hugo-theme-yuki.git",
    "https://github.com/themefisher/restaurant-hugo.git",
    "https://github.com/koirand/pulp.git",
    "https://github.com/JugglerX/hugo-whisper-theme.git",
    "https://github.com/EmielH/stip-hugo.git",
    "https://github.com/zwbetz-gh/cayman-hugo-theme.git",
    "https://github.com/vividvilla/ezhil.git",
    "https://github.com/danielkvist/hugo-piercer-theme.git",
    "https://github.com/pacollins/hugo-future-imperfect-slim.git",
    "https://github.com/jeremybise/twentynineteen-hugo.git",
    "https://github.com/tosi29/inkblotty.git",
    "https://github.com/bjacquemet/personal-web.git",
    "https://github.com/jacobsun/edidor.git",
    "https://github.com/darshanbaral/kitab.git",
    "https://github.com/themefisher/kross-hugo-portfolio-template.git",
    "https://github.com/themefisher/parsa-hugo.git",
    "https://github.com/okkur/syna.git",
    "https://github.com/bake/solar-theme-hugo.git",
    "https://github.com/jacobsun/hugo-theme-cole.git",
    "https://github.com/mmrath/hugo-bootstrap.git",
    "https://github.com/edavidaja/docter.git",
    "https://github.com/hadisinaee/avicenna.git",
    "https://github.com/darshanbaral/khata.git",
    "https://gitlab.com/VincentTam/huginn.git",
    "https://github.com/PippoRJ/hugo-refresh.git",
    "https://github.com/spech66/bootstrap-bp-hugo-startpage.git",
    "https://github.com/niklasbuschmann/contrast-hugo.git",
    "https://github.com/zzzmisa/hugo-theme-doors.git",
    "https://github.com/cdeck3r/OneDly-Theme.git",
    "https://github.com/RCJacH/hugo-webslides.git",
    "https://github.com/onweru/newsroom.git",
    "https://github.com/reuixiy/hugo-theme-meme.git",
    "https://github.com/humrochagf/colordrop.git",
    "https://github.com/jsnjack/hugo-changelog-theme.git",
    "https://github.com/g1eny0ung/hugo-theme-dream.git",
    "https://github.com/st-wong/hugo-spectre-pixel-theme.git",
    "https://github.com/orf/bare-hugo-theme.git",
    "https://github.com/spech66/materialize-bp-hugo-theme.git",
    "https://github.com/mcrwfrd/hugo-frances-theme.git",
    "https://github.com/kritoke/darksimplicity.git",
    "https://github.com/themefisher/Hargo-hugo-ecommerce-theme.git",
    "https://github.com/themefisher/liva-hugo.git",
    "https://github.com/cowboysmall-tools/hugo-devresume-theme.git",
    "https://github.com/MeiK2333/github-style.git",
    "https://github.com/spaghettiwews/hugonews.git",
    "https://github.com/zzossig/hugo-theme-zzo.git",
    "https://github.com/cowboysmall-tools/hugo-business-frontpage-theme.git",
    "https://github.com/xiaoheiAh/hugo-theme-pure.git",
    "https://github.com/Y4er/hugo-theme-easybook.git",
    "https://gitlab.com/kskarthik/resto-hugo.git",
    "https://github.com/themefisher/northendlab-hugo.git",
    "https://github.com/knadh/hugo-ink.git",
    "https://github.com/ianrodrigues/hugo-tailwind-journal.git",
    "https://github.com/dillonzq/LoveIt.git",
    "https://github.com/mattstratton/castanet.git",
    "https://github.com/google/docsy.git",
    "https://github.com/themefisher/Influencer-hugo.git",
    "https://github.com/AmazingRise/hugo-theme-diary.git",
    "https://github.com/ertuil/erblog.git",
    "https://github.com/forestryio/hugo-theme-novela.git",
    "https://gitlab.com/kskarthik/monopriv.git",
    "https://github.com/mismith0227/hugo_theme_pickles.git",
    "https://github.com/dataCobra/hugo-vitae.git",
    "https://github.com/yanlinlin82/simple-style.git",
    "https://github.com/cntrump/hugo-notepadium.git",
    "https://github.com/kdevo/osprey-delight.git",
    "https://github.com/puresyntax71/hugo-theme-chunky-poster.git",
    "https://github.com/asurbernardo/amperage.git",
    "https://github.com/NormandErwan/Blogpaper.git",
    "https://github.com/radity/raditian-free-hugo-theme.git",
    "https://github.com/kc0bfv/ticky_tacky_dark.git",
    "https://github.com/jonathanjanssens/hugo-casper3.git",
    "https://github.com/kongdivin/hugo-theme-okayish-blog.git",
    "https://github.com/themefisher/educenter-hugo.git",
    "https://github.com/pravin/hugo-theme-prav.git",
    "https://github.com/capnfabs/paperesque.git",
    "https://github.com/plopcas/papaya.git",
    "https://github.com/peaceiris/hugo-theme-iris.git",
    "https://github.com/Somrat37/somrat.git",
    "https://github.com/onweru/compose.git",
    "https://github.com/surajmandalcell/potato-dark.git",
    "https://github.com/kimcc/hugo-theme-noteworthy.git",
    "https://github.com/zzossig/hugo-theme-zdoc.git",
    "https://github.com/alexandrevicenzi/soho.git",
    "https://github.com/tastaturtier/someparts-hugo.git",
    "https://github.com/Chen-Zhe/photo-grid.git",
    "https://github.com/matsuyoshi30/harbor.git",
    "https://github.com/Mitrichius/hugo-theme-anubis.git",
    "https://github.com/softwareyoga/ronu-hugo-theme.git",
    "https://github.com/mavidser/hugo-rocinante.git",
    "https://github.com/pjbakker/flexible-seo-hugo.git",
    "https://gitlab.com/maxlefou/hugo.386.git",
    "https://github.com/austingebauer/devise.git",
    "https://github.com/amzrk2/hugo-theme-fuji.git",
    "https://github.com/invinciblycool/lekh.git",
    "https://github.com/athul/archie.git",
    "https://github.com/darshanbaral/ghazal.git",
    "https://github.com/saadnpq/npq-hugo.git",
    "https://github.com/pavel-pi/kiss-em.git",
    "https://github.com/vantagedesign/ace-documentation.git",
    "https://github.com/fourtyone11/origin-hugo-theme.git",
    "https://github.com/kc0bfv/autophugo.git",
    "https://github.com/marketempower/axiom.git",
    "https://github.com/lxndrblz/anatole.git",
    "https://github.com/rafed/ramium.git",
    "https://github.com/themefisher/twenty-twenty-hugo.git",
    "https://github.com/mrmierzejewski/hugo-theme-console.git",
    "https://github.com/wayjam/hugo-theme-mixedpaper.git",
    "https://github.com/aanupam23/hugo-sugoi.git",
    "https://github.com/StaticMania/roxo-hugo.git",
    "https://github.com/LukasJoswiak/etch.git",
    "https://github.com/yoshiharuyamashita/blackburn.git",
    "https://github.com/your-identity/hugo-theme-dimension.git",
    "https://github.com/wangchucheng/hugo-eureka.git",
    "https://github.com/urjaacharya/redgood.git",
    "https://github.com/colorchestra/smol.git",
    "https://github.com/10mohi6/hugo-theme-simple-blog.git",
    "https://github.com/dewittn/hugo-html5up-alpha.git",
    "https://github.com/heyeshuang/hugo-theme-tokiwa.git",
    "https://github.com/rhnvrm/bodhi.git",
    "https://github.com/jakewies/hugo-theme-codex.git",
    "https://github.com/apvarun/showcase-hugo-theme.git",
    "https://github.com/7ma7X/HugoTeX.git",
    "https://github.com/hossainemruz/toha.git",
    "https://github.com/gevhaz/hugo-theme-notrack.git",
    "https://github.com/varkai/hugo-theme-zozo.git",
    "https://gitlab.com/rmaguiar/hugo-theme-color-your-world.git",
    "https://github.com/themefisher/persian-hugo.git",
    "https://gitlab.com/toryanderson/hugo-icarus.git",
    "https://github.com/samrobbins85/hugo-developer-portfolio.git",
    "https://github.com/rmsubekti/the-roots-home.git",
    "https://github.com/themefisher/academia-hugo.git",
    "https://github.com/J-Siu/hugo-theme-sk1.git",
    "https://github.com/mdashx/basicwebtheme.git",
    "https://github.com/ThemeTony/hugo-theme-tony.git",
    "https://github.com/chipzoller/hugo-clarity.git",
    "https://github.com/monkeyWzr/hugo-theme-cactus.git",
    "https://github.com/leonardofaria/bento.git",
    "https://github.com/J-Siu/hugo-theme-sk2.git",
    "https://github.com/J-Siu/hugo-theme-sk3.git",
    "https://github.com/epistemehealth/health-science-journal.git",
    "https://github.com/caressofsteel/hugo-story.git",
    "https://github.com/janraasch/hugo-scroll.git",
    "https://github.com/rz3n/hugo-theme-freshstart.git",
    "https://github.com/gangjun06/SimpleIntro.git",
    "https://github.com/ojroques/hugo-researcher.git",
    "https://github.com/jmablog/hugo-clinic-notes.git",
    "https://github.com/queensferryme/hugo-theme-texify.git",
    "https://github.com/vjeantet/hugo-theme-docport.git",
    "https://github.com/djuelg/Shapez-Theme.git",
    "https://github.com/negrel/hugo-theme-pico.git",
    "https://github.com/ineesalmeida/almeida-cv.git",
    "https://github.com/opera7133/Blonde.git",
    "https://github.com/StaticMania/portio-hugo.git",
    "https://github.com/thegeeklab/hugo-geekblog.git",
    "https://gitlab.com/mertbakir/resume-a4.git",
    "https://github.com/thegeeklab/hugo-geekdoc.git",
    "https://github.com/janraasch/hugo-bearblog.git",
    "https://github.com/janraasch/hugo-product-launch.git",
    "https://github.com/adityatelange/hugo-PaperMod.git",
    "https://github.com/CaiJimmy/hugo-theme-stack.git",
    "https://github.com/themefisher/bigspring-hugo-startup-theme.git",
    "https://github.com/leonstafford/accessible-minimalism-hugo-theme.git",
    "https://github.com/Softorage/HugoTheme-VibrantShadows.git",
    "https://github.com/gurusabarish/hugo-profile.git",
    "https://github.com/cristianmarint/sicily-hugo-theme.git",
    "https://github.com/s4n7h0/hugo-theme-timeline.git",
    "https://github.com/RainerChiang/simpleness.git",
    "https://github.com/tylerjlawson/simple-resume.git"

]
